// server.js
import express from "express";
import cors from "cors";
import type { Request, Response } from "express";
import bodyParser from "body-parser";
import swaggerUi from "swagger-ui-express";
import { RegisterRoutes } from "./src/routes"; // generated by tsoa
import * as swaggerJson from "./src/swagger.json";


const app = express();
app.use(bodyParser.urlencoded({ extended: true })); //????
app.use(bodyParser.json());

app.use(cors({
  origin: "http://localhost:5173",  // or "*"
  methods: ["GET","POST","PUT","DELETE"],
  allowedHeaders: ["Content-Type"]
}));

// Register tsoa-generated routes
RegisterRoutes(app);

// Serve Swagger UI
app.use("/docs", swaggerUi.serve, swaggerUi.setup(swaggerJson));

// Root endpoint
app.get("/", (req: Request, res: Response) => {
  res.send("✅ Express + tsoa server is running. Docs at /docs");
});

const PORT = process.env.PORT || 3000;
app.listen(PORT, () => {
  console.log(`🚀 Server ready at http://localhost:${PORT}`);
  console.log(`📖 Swagger UI available at http://localhost:${PORT}/docs`);
});

